### ISSUE TITLE
Add periods to the semester representation in API

### ISSUE THREAD

**Issue by jirutka** [cvut/sirius#127]
User front-end (fittable on FIT and FELsight on FEL) should display name of the current period with ordinal number of a week in that period (e.g. “5th teaching week”, “3rd exam week”, “holiday”). We have three “periods” in a semester: teaching, exam and holiday (summer, and winter during Christmas). Perhaps we can say that we have one more period, something like “undefined…”

The problem is that we don’t have any information about holiday period in the `/semester` resource. Holiday is actually a schedule exception, but that’s not much convenient source to derive information about period. Sometimes we can infer this information from difference between `exams_end_at` and `ends_at`, but it may be wrong (e.g. exam period interrupted by winter holiday).

We’ve been discussing this problem and eventually we agreed on the following. Add attribute _periods_ with array of periods to the semester representation; each period must have _from_ (date), _to_ (date), and `type` (`teaching`, `exam`, and `holiday`).

```json
{
  "periods": [
    {
      "from": "2015-02-16",
      "to": "2015-05-15",
      "type": "teaching"
    },
    {
      "from": "2015-05-18",
      "to": "2015-06-26",
      "type": "exam"
    },
    {
      "from": "2015-06-29",
      "to": "2015-08-28",
      "type": "holiday"
    }
  ]
}
```

This will make attributes `exams_start_at`, `exams_end_at`, and `teaching_ends_at` deprecated, but we should keep them for backward compatibility (until API v2). It’s kinda important to have final number of types to avoid abusing this structure for something that should be in schedule exceptions (there’s a small overlap already).

Periods may overlap; for example, if we have exam period from 2015-12-18 to 2016-02-15 and winter holiday from 2015-12-23 to 2015-12-31, then there should be just one exam period. I hope that this will be more easy for clients to work with.

**Comment by jirutka** [comment]
@rochmich (FEL) needs this functionality till August 31th, so we should finish this task during next week.

**Comment by jnv** [comment]
Do we have any plan how to actually implement this? Should these data be calculated and cached or materialised in a database?

**Comment by jnv** [comment]
Wait, periods are actually semesters data, so it makes sense to materialise them.

Still I am not sure (or remind me), how do we solve weeks numbering/parity?

**Comment by jirutka** [comment]
Of course we have. ಠ_ಠ What do you think, that I’m creating issues just for fun?

**Comment by jnv** [comment]
Oh my, did I say anything wrong? I am sorry for asking.

**Comment by jirutka** [comment]
Eh, sorry, I’ve missed “how” in your comment, so it has sound like you denies this issue.

**Comment by jirutka** [comment]
> Should these data be calculated and cached or materialised in a database?

B is right.

> Still I am not sure (or remind me), how do we solve weeks numbering/parity?

The purpose of this change is to provide semester milestones in a form that will allow clients to do week numbering easily on their own, i.e. it’ll be client’s responsibility.

**Comment by jnv** [comment]
> The purpose of this change is to provide semester milestones in a form that will allow clients to do week numbering easily on their own, i.e. it’ll be client’s responsibility.

Okay, I guess that makes sense, we can review this in later versions of API. One thing though: weeks parity can be different from calendar year, can't it? Then you would need to also provide this information to the client.

**Comment by jirutka** [comment]
> …weeks parity can be different from calendar year, can't it? Then you would need to also provide this information to the client.

Yeah, and we already expose this information (`first_week_parity`):

```json
{
  "semesters": [
    {
      "id": "18000-B142",
      "semester": "B142",
      "faculty": 18000,
      "starts_at": "2015-02-16",
      "ends_at": "2015-09-21",
      "exams_start_at": "2015-05-18",
      "exams_end_at": "2015-06-27",
      "teaching_ends_at": "2015-05-16",
      "first_week_parity": "even",
      "hour_duration": 45,
      "hour_starts": [
        "07:30", "08:15", "09:15", "10:00", "11:00", "11:45",
        "12:45", "13:30", "14:30", "15:15", "16:15", "17:00",
        "18:00", "18:45", "19:45"
      ]
    }
  ],
  "meta": {
    "count": 4,
    "offset": 0,
    "limit": 1
  }
}
```

**Comment by jnv** [comment]
:+1: I think `first_week_parity` should be part of `teaching` period.

**Comment by jnv** [comment]
Initially the problem is simple: we could infer periods from semester attributes (`starts_at`, `teaching_ends_at` etc.). But holidays can split the `teaching` period into two, e.g. we have the Xmas break and then there is one more week of teaching.
Since we represent holidays as schedule exceptions, we could add a new attribute to an exception: whether the exception affects semester's periods. This could be a binary value (e.g. `affects_periods`), but then, how do we know what kind of period the exception represents? So, the exceptions will have a new attribute, e.g. `period={holiday,teaching,exam}`.
This way we have a nice mapping of schedule exceptions to periods, e.g. winter break or summer break must be entered as schedule exceptions which also affect semester.

The biggest issue is what we do about weeks' parity. Consider a teaching week which starts after the winter break; is it even or odd? That's an administrative decision. We would need to add schedule exception to shift relevant events. But we have no device to represent week's parity for client. And theoretically we may end up with _more_ events, than in the original schedule; this cannot be handled by schedule exception: exceptions won't generate new events by design.

**Comment by jnv** [comment]
So we have concluded that semester periods should affect the scheduling process. Currently we treat the teaching period as a continuous time period for which events are generated. If we treat periods as a feature of semester, we can generate only events which should be scheduled.

The nice effect of this approach that we can clearly decide between “regular” and “irregular” schedule exceptions: events won’t be scheduled outside of the teaching block in the first place, so schedule exceptions handle only individual free days and arbitrary administrative decisions.

There is one important caveat: since periods affect the scheduling process, change in the periods will break the synchronisation. We _assume_ that time periods remain immutable throughout the semester. Should the periods change, whole semester would have to be rescheduled from scratch.

**Comment by jnv** [comment]
But since we need this quickly, I suppose we will have to wait a bit before complete change of scheduling process.

We can either introduce a new model, or an attribute for the semester, which represent time periods within the semester (we think model would be better for extension and validation; plus we'd need JSONB for an attribute).
Later we will use this data for scheduling process.

**Comment by kalvotom** [comment]
> Yeah, and we already expose this information (first_week_parity):

I am afraid that this is not sufficient. Parity of a week does not have to be "regular".

In particular, the [official FIT schedule for B151](https://fit.cvut.cz/sites/default/files/STO/Casovy%20plan%20AR%202015%20-%2016_0.pdf) defines the last week (13th week of semester, 1st week of the year) to be *even*, although the first week is *odd*. I suppose this choice is faculty dependent.

**Comment by jnv** [comment]
That's precisely what we have discussed today. All non-continuous teaching periods will have to explicitly state the first week's parity.

**Comment by kalvotom** [comment]
Oh, so `first_week_parity` is a property of every connected component of a teaching period? I like it :-).

**Comment by jnv** [comment]
We have settled on the following representation:

```json
{
  ...
  "periods": [
    {
      "from": "2015-10-06",
      "to": "2016-12-20",
      "type": "teaching",
      "first_week_parity": "odd"
    },
    {
      "from": "2015-12-21",
      "to": "2016-01-03",
      "type": "holiday"
    },
    {
      "from": "2015-01-04",
      "to": "2015-01-11",
      "type": "teaching",
      "first_week_parity": "even"
    },
    {
      "from": "2015-01-12",
      "to": "2015-02-28",
      "type": "exams"
    }
   ...
  ]
}
```

Dates are bogus, but I hope it shows our point.

The one last thing we are not clear on yet is what to do about “undefined” periods of semester, e.g. between exams and the start of new semester. We could probably expose them with something like `type: "undefined"`. Or perhaps we could keep the semester's start/end dates around and omit these periods from the list.

**Comment by jnv** [comment]
This is now pending review in #130.
