### ISSUE TITLE
Missing one time events

### ISSUE THREAD

**Issue by jnv** [cvut/sirius#151]
> …v kalendáři se mi zatím nezobrazují jednorázové akce, konkrétně   **Test: Přípravný kurz matematiky,** 1.10. 2015 v 15:45.

**Comment by jnv** [comment]
The event is in KOSapi, it is not associated with any course, but most notably, it is outside of any semester.

One time events should not be affected by semesters; we should either virtually expand semester dates to fill in any gaps, or include events without any semester association.

**Comment by kalvotom** [comment]
Author of the event speaking.

This can really happen and it is not a mistake. PKM is not a real course and it does not exist in KOS, yet. KOS (teacher web GUI) does not allow you to create an event in semester with no associated course. Consequently, any event that is intended for students of many courses will not be associated with a semester.

![kos_akce](https://cloud.githubusercontent.com/assets/919079/10187508/5f29b74a-6759-11e5-9f35-33ec267cb6fe.png)

**Comment by jnv** [comment]
Oh okay. So it would be probably preferable to bypass KOS's constraints and put these events manually into Sirius.

**Comment by flexik** [comment]
One time events loaded from KOSapi into Sirius are matched by semester start/end date, not by semester association (because of this KOS limitation).

Currently in Sirius the B142 semester is for some reason configured to end at 2015-09-21 ([officially](http://fit.cvut.cz/sites/default/files/STO/asov%C3%BD%20pl%C3%A1n%20akademick%C3%A9ho%20roku%202014%20-%2015_5.pdf) the end date should be 2015-09-30) and B151 starts at 2015-10-05. This course event is in the semester gap, thus it is not being imported.

In my opinion we should fill in the semester dates to not have any in between gaps, which would avoid this problem completely.

**Comment by jnv** [comment]
Yeah, but we just follow the official schedule. So the question is, whether we can somewhat bend the rules for the system. Perhaps we could expose official date externally, but work internally with a longer semester.

**Comment by jnv** [comment]
Bumping this up again. The issue is clearly visible with BI-AG1, see [Timetable](https://timetable.fit.cvut.cz/old/public/cz/akce/index.html) and [Fittable](https://timetable.fit.cvut.cz/new/courses/BI-AG1?date=2017-01-20) – one-off events are missing.
Also, [on Jan 6](https://timetable.fit.cvut.cz/new/courses/BI-AG1?date=2017-01-06) there is event which is not reported elsewhere, what is it?
