### ISSUE TITLE
Do not request a new access token for every single request

### ISSUE THREAD

**Issue by jirutka** [cvut/sirius#160]
Access token is shared only within a single instance of UmapiClient, which is initialized for every request. This basically means that we request a new access token for every single request (i.e. totally unnecessary extra HTTP request to OAAS).

See [./lib/sirius_api/umapi_client.rb](https://github.com/cvut/sirius/blob/c482cd2759137cabf0c8fe251f4613f742934299/lib/sirius_api/umapi_client.rb).

**Comment by flexik** [comment]
How should we handle this? One possible option is to store the state in `Thread.current`, which saves it only for the current thread, which is not ideal. The other options is to use external store like Redis, which works for the whole app and should be thread safe.

I don't like storing the state in global variable / class variable/ class instance variable, because there are threading issues and the state is not shared between other workers anyways.

**Comment by jnv** [comment]
Shared memory has the downside of synchronisation locking. It is very likely multiple threads will attempt to refresh token at the same time, so we would need to introduce some kind of global lock too. Perhaps there is some useful abstraction for this. Otherwise keeping token on a thread level seems like an acceptable compromise and a still a huge improvement to me.

**Comment by flexik** [comment]
I guess we should use `Thread.current` for now and decrease amount of Puma threads. There are currently 3 DB connections per worker anyways, so 16 threads max is a bit overkill.

**Comment by flexik** [comment]
Resolved in 03d4bcb9c1f94698b63de44060b1885e53565347.
