### ISSUE TITLE
Dependency git://github.com/jnv/role_playing.git vanished

### ISSUE THREAD

**Issue by jirutka** [cvut/sirius#232]
@jnv, why the heck did you delete jnv/role_playing?!

**Comment by jnv** [comment]
@jirutka Sorry, I was cleaning up merged forks and had no idea this thing was still used. I have re-forked the repo, the locked commit is present: https://github.com/jnv/role_playing/commit/8bfab60b5308993926c0f5acfd5d7d404ca0c44d

Since the commit was merged, role_playing from RubyGems should be used, v0.1.5.
